KAFKA_SERVERS: 3.112.249.48:9092
REDIS_HOST: 3.112.249.48
REDIS_PORT: 6379
SHOW_SQL: false
SERVER_PORT: 7070
DB_HOST: localhost
DB_PORT: 27017
DB_NAME: iam
DB_SCHEMA: cms
DB_USER: mongo
DB_PASSWORD: mongo
